apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
spec:
  tls:
  - hosts:
    - wecgwm.com
    secretName: tls-secret
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /echo
        pathType: Exact 
        backend:
          service:
            name: echo
            port:
              number: 80
