apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  #annotations:
    # nginx.ingress.kubernetes.io/app-root: "/grafana"
  name: grafana
  namespace: monitoring
spec:
  tls:
  - hosts:
    - monitor.wecgwm.com
    secretName: tls-secret
  ingressClassName: nginx
  rules:
  - host: monitor.wecgwm.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
