apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-k8s 
  namespace: ingress-nginx
spec:
  endpoints:
  - port: prometheus 
  selector:
    matchLabels:
      app.kubernetes.io/instance: ingress-nginx
